### ISSUE TITLE
PicklingError: Can't pickle <function CropForegroundd. at 0x0000028FCC417510>:

### ISSUE THREAD

**Issue by oscarramirezs** [Project-MONAI/MONAI#1583]
Hi I'm new to MONAI and Pytorch with MAC,

im using the new Mac M1 with GPU and CPU.

I run  the spleen_segmentation_3d.ipynb.', but while it displayed 'epoch 1/600', PickingError raised.
PicklingError: Can't pickle <function CropForegroundd. at 0x0000028FCC417510>: attribute lookup CropForegroundd. on monai.transforms.croppad.dictionary failed
Please tell me how to fix this error.

actually say also when I run "device = torch.device("cuda:0")": I got -> Torch not compiled with CUDA enabled, so I decided to run with cpu, are both errors linked? 
MONAI support MAC 2020 M1? 
 thank Oscar

**Comment by Nic-Ma** [comment]
Hi @oscarramirezs ,

Thanks for your interest with MONAI project.
Sorry we didn't test MONAI APIs with M1 chip, but we have some basic CI tests on Mac OS.
Hi @IsaacYangSLA @madil90 , could you guys please help share something about Mac ENV? Can we enable some GPU tests on Mac in future?

Thanks.

**Comment by rijobro** [comment]
Hi @oscarramirezs, how did you install pytorch? From [this thread](https://discuss.pytorch.org/t/installing-pytorch-on-m1-macbook/105961) (2 months ago), it seems that pytorch binaries aren't available for the M1 macs, meaning pytorch needs to be installed from source; is that what you did? (I'm not sure if the information from 2 months ago is already out of date!)

Could you print the output of:
```bash
python -c "from monai.config import print_debug_info; print_debug_info()"
```

**Comment by oscarramirezs** [comment]
Hi rijobro 

I did thought 

-> conda install pytorch torchvision -c pytorch

----------------------
To ensure that PyTorch was installed correctly, we can verify the installation by running sample PyTorch code. Here we will construct a randomly initialized tensor.
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939],
        [0.5185, 0.6977, 0.8000]])
-------------
and it worked

Oscar

**Comment by rijobro** [comment]
Ok, and what happens if you change `num_workers=4` to  `num_workers=1` throughout the spleen example?

**Comment by wyli** [comment]
duplicate of  https://github.com/Project-MONAI/MONAI/issues/787?

**Comment by oscarramirezs** [comment]
Hi, 

In the "monai.transforms" I "#"  the #CropForegroundd(keys=["image", "label"], source_key="image") and it works
